# Generated by Django 4.0.4 on 2022-04-28 20:16

import app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('owned_by', models.UUIDField(db_index=True, unique=True)),
                ('token', models.TextField(db_index=True, default=app.models.token_string, unique=True)),
                ('enabled_at', models.DateTimeField(null=True)),
                ('disabled_at', models.DateTimeField(null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('is_withdrawal', models.BooleanField()),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('party_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
            ],
        ),
    ]
