# Generated by Django 4.0.4 on 2022-04-29 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField()),
                ('is_withdrawal', models.BooleanField()),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('transacted_by', models.UUIDField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4)),
                ('reference_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wallet')),
            ],
        ),
    ]
