# Generated by Django 4.0.4 on 2022-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transaction_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transacted_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposited_by',
            field=models.UUIDField(null=True),
        ),
    ]
