# Generated by Django 4.0.4 on 2022-04-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transaction_transacted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deposited_by',
        ),
    ]
